# Configurações de Diretórios para o Projeto
paths:
  config_dir: 'D:/Github/data-science/projetos/rotatividade-de-clientes/machine-learning/config/'
  logs_dir: 'D:/Github/data-science/projetos/rotatividade-de-clientes/machine-learning/logs/'
  notebook_dir: 'D:/Github/data-science/projetos/rotatividade-de-clientes/machine-learning/notebook/'
  src_dir: 'D:/Github/data-science/projetos/rotatividade-de-clientes/machine-learning/src/'

# Caminhos para o Armazenamento de Modelos
models:
  directory: 'D:/Github/data-science/projetos/rotatividade-de-clientes/machine-learning/models/'
  scaler: 'D:/Github/data-science/projetos/rotatividade-de-clientes/machine-learning/models/scaler.joblib'
  final_model: 'D:/Github/data-science/projetos/rotatividade-de-clientes/machine-learning/models/final_model.joblib'

# Caminhos para Pré-processadores
preprocessors:
  path: 'D:/Github/data-science/projetos/rotatividade-de-clientes/machine-learning/preprocessors/preprocessor.joblib'
  input_features:  # Adicionado para a inferência
    - CreditScore
    - Age
    - Tenure
    - Balance
    - NumOfProducts
    - HasCrCard
    - IsActiveMember
    - EstimatedSalary
    - Geography_France
    - Geography_Germany
    - Geography_Spain
    - Gender_Female
    - Gender_Male

# Caminhos para os Dados
data:
  raw: 'D:/Github/data-science/projetos/rotatividade-de-clientes/machine-learning/data/raw/rclientes.csv'
  data_processed: 'D:/Github/data-science/projetos/rotatividade-de-clientes/machine-learning/data/processed/rclientes_dados_tratados.csv'
  processed: 'D:/Github/data-science/projetos/rotatividade-de-clientes/machine-learning/data/processed/rclientes_preprocessado.csv'
  new_data: 'D:/Github/data-science/projetos/rotatividade-de-clientes/machine-learning/data/new_data.csv'

# Configurações de Relatórios
reports:
  directory: 'D:/Github/data-science/projetos/rotatividade-de-clientes/machine-learning/reports/'
  figures_dir: 'D:/Github/data-science/projetos/rotatividade-de-clientes/machine-learning/reports/figures/'
  classification_initial: 'D:/Github/data-science/projetos/rotatividade-de-clientes/machine-learning/reports/classification_initial.txt'
  classification_final: 'D:/Github/data-science/projetos/rotatividade-de-clientes/machine-learning/reports/classification_final.txt'
  classification_threshold: 'D:/Github/data-science/projetos/rotatividade-de-clientes/machine-learning/reports/classification_threshold.txt'

# Configurações de Pré-processamento
preprocessing:
  numeric_features: ["CreditScore", "Age", "Tenure", "Balance", "EstimatedSalary"]
  categorical_features: ["Geography", "Gender", "HasCrCard", "IsActiveMember"]

# Configurações de Previsões
predictions:
  output: 'D:/Github/data-science/projetos/rotatividade-de-clientes/machine-learning/predictions/predictions.csv'
  directory: 'D:/Github/data-science/projetos/rotatividade-de-clientes/machine-learning/predictions/'
