# Configuração Inicial do Projeto de Análise de Compartilhamento de Viagem

paths:
  config_dir: 'D:/Github/data-science/projetos/logistica_transporte/3_analise_desempenho_viagens_agrupadas_clusterização_series_temporais/config/'
  logs_dir: 'D:/Github/data-science/projetos/logistica_transporte/3_analise_desempenho_viagens_agrupadas_clusterização_series_temporais/logs/'
  notebook_dir: 'D:/Github/data-science/projetos/logistica_transporte/3_analise_desempenho_viagens_agrupadas_clusterização_series_temporais/notebook/'
  src_dir: 'D:/Github/data-science/projetos/logistica_transporte/3_analise_desempenho_viagens_agrupadas_clusterização_series_temporais/src/'

models:
  directory: 'D:/Github/data-science/projetos/logistica_transporte/3_analise_desempenho_viagens_agrupadas_clusterização_series_temporais/models/'
  scaler: 'D:/Github/data-science/projetos/logistica_transporte/3_analise_desempenho_viagens_agrupadas_clusterização_series_temporais/models/scaler.joblib'
  final_model: 'D:/Github/data-science/projetos/logistica_transporte/3_analise_desempenho_viagens_agrupadas_clusterização_series_temporais/models/final_model.joblib'

preprocessors:
  path: 'D:/Github/data-science/projetos/logistica_transporte/3_analise_desempenho_viagens_agrupadas_clusterização_series_temporais/preprocessors/preprocessor.joblib'

data:
  raw: 'D:/Github/data-science/projetos/logistica_transporte/3_analise_desempenho_viagens_agrupadas_clusterização_series_temporais/data/raw/logistica_transportadora_2018_2022.csv'
  processed: 'D:/Github/data-science/projetos/logistica_transporte/3_analise_desempenho_viagens_agrupadas_clusterização_series_temporais/data/processed/processado.parquet'

reports:
  directory: 'D:/Github/data-science/projetos/logistica_transporte/3_analise_desempenho_viagens_agrupadas_clusterização_series_temporais/reports/'
  figures_dir: 'D:/Github/data-science/projetos/logistica_transporte/3_analise_desempenho_viagens_agrupadas_clusterização_series_temporais/reports/figures/'

metrics:
  directory: 'D:/Github/data-science/projetos/logistica_transporte/3_analise_desempenho_viagens_agrupadas_clusterização_series_temporais/metrics/'

# Requisitos do Ambiente
python:
  version: '3.8'
