# Configuração Inicial do Projeto de Churn de Clientes

paths:
  config_dir: "D:/github/data-science/projetos/risco_credito/config/config.yaml"
  logs_dir: "D:/github/data-science/projetos/risco_credito/logs/"
  notebook_dir: "D:/github/data-science/projetos/risco_credito/notebook/"
  src_dir: "D:/github/data-science/projetos/risco_credito/src/"
  figures_dir: "D:/github/data-science/projetos/risco_credito/reports/figures"
  reports_dir: "D:/github/data-science/projetos/risco_credito/reports"  # <-- Adicione esta linha

models:
  directory: "D:/github/data-science/projetos/risco_credito/models"
  final_model: "D:/github/data-science/projetos/risco_credito/models/final_model.joblib"
  versioned_models: "D:/github/data-science/projetos/risco_credito/models/versioned/"

preprocessors:
  preprocessor_path: "D:/github/data-science/projetos/risco_credito/preprocessors/preprocessor.joblib"
  scaler_path: "D:/github/data-science/projetos/risco_credito/preprocessors/scaler.joblib"

data:
  raw: "D:/github/data-science/projetos/risco_credito/data/raw/risco_credito.parquet"
  processed_parquet: "D:/github/data-science/projetos/risco_credito/data/processed/processed.parquet"

logs:
  file: "D:/github/data-science/projetos/risco_credito/logs/data_processing.log"

reports:
  figures: "D:/github/data-science/projetos/risco_credito/reports/figures/"

metrics:
  directory: "D:/github/data-science/projetos/risco_credito/metrics"

explainability:
  shap_values: "D:/github/data-science/projetos/risco_credito/reports/shap_values.csv"
  shap_figures: "D:/github/data-science/projetos/risco_credito/reports/figures/shap_summary.png"

thresholds:
  optimal_threshold_path: "D:/github/data-science/projetos/risco_credito/models/optimal_threshold.txt"

python:
  version: "3.8"
